set IDENTITY_INSERT NT_PARAMETRE_001 ON
INSERT INTO NT_PARAMETRE_001(ID, PARENTID, NAME, VALUE, ACTIVE)select ID, PARENTID, NAME, VALUE, ACTIVE from NT_PARAMETRE_991
set IDENTITY_INSERT NT_PARAMETRE_001 OFF